import json

from tqdm import tqdm
import numpy as np

from logparser import query


def hmtl_table(query_str):
    names, res = query(query_str)
    body = list()
    body.append('<table class="table"><thead><tr>')
    body.extend(f'<th scope="col">{h}</th>' for h in names)
    body.append("</tr></thead><tbody>")
    for row in res:
        body.append("<tr>")
        for val in row:
            body.append(f"<td>{val}</td>")
        body.append("</tr>")
    body.append("</tbody></table>")
    return ''.join(body)


def players():
    body = hmtl_table("SELECT player, COUNT(mid) as rounds FROM participates GROUP BY player ORDER BY rounds DESC")
    card = {
        'header': 'Players',
        'body': body
    }
    return card


def maps():
    body = hmtl_table("SELECT map, COUNT(mid) as count FROM match GROUP BY map ORDER BY count DESC")
    card = {
        'header': 'Maps',
        'body': body
    }
    return card
    
    
def win_loss():
    _, win = query("SELECT part.player, COUNT(part.mid) as wins \
    FROM participates as part JOIN match ON part.mid == match.mid JOIN roles on part.role == roles.role \
    WHERE roles.team = match.result GROUP BY part.player ORDER BY part.player")
    _, loss = query("SELECT part.player, COUNT(part.mid) as wins \
    FROM participates as part JOIN match ON part.mid == match.mid JOIN roles on part.role == roles.role \
    WHERE roles.team != match.result GROUP BY part.player ORDER BY part.player")
    players = [p for p, c in win]
    wins = [c for p, c in win]
    losses = [c for p, c in loss]
    quotes = [np.round(w / (w+l), decimals=3) for w, l in zip(wins, losses)]
    data = list(zip(players, wins, losses, quotes))
    data.sort(key=lambda d: d[3], reverse=True)
    body = ["""
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Player</th>
                    <th scope="col">wins</th>
                    <th scope="col">losses</th>
                    <th scope="col">quote</th>
                </tr>
            </thead>
            <tbody>
    """]
    body.extend([f"<tr><td>{p}</td><td>{w}</td><td>{l}</td><td>{q}</td></tr>" for p, w, l, q in data])
    body.append("</tbody></table>")
    card = {
        'header': 'Siege',
        'body': ''.join(body)
    }
    return card
    
    
if __name__ == "__main__":
    cards = []
    
    # quick text cards as result of queries
    queries = [
        ("Played games", "SELECT COUNT(mid) as matches FROM match"),
        ("Who won how often?", "SELECT COUNT(mid) as wins, result as team FROM match GROUP BY result")
    ]
    for q in tqdm(queries):
        _, res = query(q[1])  # list of tuples
        res = [str(e) for tuple in res for e in tuple]
        res = " ".join(res)
        cards.append({"header": q[0], "text": res})
        
    # more complex cards created by functions
    cards.append(players())
    cards.append(maps())
    cards.append(win_loss())
        
    # write js script
    with open("./Frontend/cards.js", "w") as f:
        f.write("/* autogenerated file */\n")
        f.write("const cards = ")
        f.write(json.dumps(cards).replace("\n", "").replace("'", "\""))
        f.write(";")